use regex::Regex;
use serde_json::Value;
use std::sync::LazyLock;

static CLEAN_USER_QUERY_RE: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"<user_query>\s*").unwrap());
static CLEAN_END_QUERY_RE: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"\s*</user_query>").unwrap());
static CLEAN_ATTACHED_RE: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"(?s)<attached_files>.*?</attached_files>").unwrap());
static CLEAN_MULTI_NL_RE: LazyLock<Regex> = LazyLock::new(|| Regex::new(r"\n{3,}").unwrap());

static STRIP_TAGS: &[&str] = &[
    "open_and_recently_viewed_files",
    "user_info",
    "system_reminder",
    "system-reminder",
    "git_status",
    "external_links",
    "rules",
    "agent_skills",
    "manually_attached_skills",
    "recommended_plugins",
    "documentation_context",
    "hooks_context",
    "agent_transcripts",
];

static STRIP_TAG_REGEXES: LazyLock<Vec<Regex>> = LazyLock::new(|| {
    STRIP_TAGS
        .iter()
        .map(|tag| Regex::new(&format!(r"(?s)<{tag}>.*?</{tag}>")).unwrap())
        .collect()
});

static START_NOISE: &[&str] = &[
    "this session is being continued from a previous conversation",
    "caveat: the messages below were generated by the user while running local commands",
    "you are claude code",
];

static SHORT_NOISE: &[&str] = &[
    "i'm currently in read-only mode",
    "i am currently in read-only mode",
    "i'm in read-only mode",
    "i cannot make changes",
    "i'm in plan mode",
    "hello! i'm claude",
    "i am claude",
    "i'm ready to help you",
    "ready to help you",
    "what would you like me to",
    "how can i assist",
    "i understand that i'm",
];

static USER_QUERY_BODY_RE: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"(?s)<user_query>\s*(.*?)\s*</user_query>").unwrap());

static WARMUP_PATTERNS: &[&str] = &["warmup", "/clear"];

static CLEAR_META_PATTERNS: &[&str] = &[
    "caveat: the messages below were generated by the user while running local commands",
    "<command-name>",
    "</command-name>",
    "<local-command-stdout>",
];

fn truncate_for_search(s: &str, max: usize) -> String {
    if s.len() <= max {
        return s.to_owned();
    }
    let head_end = s.floor_char_boundary(max * 3 / 4);
    let tail_start = s.ceil_char_boundary(s.len().saturating_sub(max / 4));
    format!("{} {}", &s[..head_end], &s[tail_start..])
}

/// Words that run the word after them as the command.
const COMMAND_WRAPPERS: &[&str] = &[
    "time", "command", "exec", "env", "nohup", "sudo", "nice", "timeout",
];
/// Shell keywords that a command follows (`for …; do chat-history …`).
const SHELL_KEYWORDS: &[&str] = &["do", "then", "else", "elif", "if", "while", "until", "!"];
/// Where the next word falls in a simple command.
#[derive(Clone, Copy)]
enum Position {
    /// The word names the command.
    Command,
    /// The word follows a wrapper and may be one of its options (`sudo -u me ch …`).
    Wrapped(Wrapper),
    /// The command is already named; the word is an argument.
    Argument,
}

#[derive(Clone, Copy)]
struct Wrapper {
    name: &'static str,
    /// The previous word was an option that takes a separate value.
    value_next: bool,
    /// `timeout` takes a duration before the command.
    duration_seen: bool,
}

/// Wrapper options whose value is the next word (`nice -n 10`).
fn wrapper_option_takes_value(wrapper: &str, option: &str) -> bool {
    match wrapper {
        "sudo" => matches!(
            option,
            "-u" | "-g"
                | "-p"
                | "-C"
                | "-D"
                | "-r"
                | "-t"
                | "-U"
                | "-T"
                | "-R"
                | "--user"
                | "--group"
                | "--prompt"
                | "--close-from"
                | "--chdir"
                | "--role"
                | "--type"
                | "--other-user"
                | "--command-timeout"
                | "--chroot"
        ),
        "env" => matches!(option, "-u" | "-C" | "--unset" | "--chdir"),
        "nice" => matches!(option, "-n" | "--adjustment"),
        "timeout" => matches!(option, "-s" | "-k" | "--signal" | "--kill-after"),
        "time" => matches!(option, "-f" | "-o" | "--format" | "--output"),
        "exec" => option == "-a",
        _ => false,
    }
}
static EMBEDDED_COMMAND_RE: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r#"\b(?:cmd|command)["']?\s*:\s*([`"'])"#).unwrap());

/// Whether a shell command, or a script that builds one, runs chat-history.
/// Only the first word of each simple command counts, so a path or an
/// argument that mentions chat-history (`cd ~/src/chat-history`) does not.
pub fn is_history_command(command: &str) -> bool {
    if shell_runs_history(command) {
        return true;
    }
    // Codex records the JavaScript or JSON that calls exec_command, not just
    // its shell argument. Inspect that argument without treating quoted grep
    // patterns in an ordinary shell command as executable commands.
    if let Ok(args) = serde_json::from_str::<Value>(command) {
        for key in ["cmd", "command"] {
            if args
                .get(key)
                .and_then(Value::as_str)
                .is_some_and(shell_runs_history)
            {
                return true;
            }
        }
    }
    if !command.contains("tools.exec_command") {
        return false;
    }
    EMBEDDED_COMMAND_RE.captures_iter(command).any(|capture| {
        let delimiter = capture[1].chars().next().unwrap();
        let mut script = String::new();
        let mut escaped = false;
        for ch in command[capture.get(0).unwrap().end()..].chars() {
            if escaped {
                script.push(ch);
                escaped = false;
            } else if ch == '\\' {
                escaped = true;
            } else if ch == delimiter {
                break;
            } else {
                script.push(ch);
            }
        }
        shell_runs_history(&script)
    })
}

fn shell_runs_history(command: &str) -> bool {
    fn mark_shell_input(
        heredocs: &mut [Heredoc],
        stdin_heredoc: &mut Option<usize>,
        shell_launcher: bool,
    ) {
        let candidate = stdin_heredoc.take();
        if shell_launcher && let Some(index) = candidate {
            heredocs[index].shell_input = true;
        }
    }

    fn first_word_is_history(
        word: &mut String,
        word_quoted: &mut bool,
        position: &mut Position,
        shell_launcher: &mut bool,
        script_next: &mut bool,
        redirect_target_next: &mut bool,
        stdin_heredoc: &mut Option<usize>,
    ) -> bool {
        let quoted = std::mem::take(word_quoted);
        if word.is_empty() {
            return false;
        }
        let token = std::mem::take(word);
        // A redirection (`>out`, `> out`, `2>&1`, `&>log`) and its target are
        // not arguments: they neither name a command nor a script path. A
        // quoted word (`bash -c '>log ch …'`) is never a redirection.
        if std::mem::take(redirect_target_next) {
            return false;
        }
        if !quoted && let Some((needs_target, stdin)) = redirection(&token) {
            // A later `</dev/null` or `<<<word` replaces a heredoc as stdin.
            if stdin {
                *stdin_heredoc = None;
            }
            *redirect_target_next = needs_target;
            return false;
        }
        if *script_next {
            *script_next = false;
            return shell_runs_history(&token);
        }
        if *shell_launcher && token.starts_with('-') && token.contains('c') {
            *script_next = true;
            *shell_launcher = false;
            return false;
        }
        if matches!(position, Position::Argument) {
            // A shell given a script path (or -c above) does not execute its
            // standard input as a script.
            if *shell_launcher && !token.starts_with('-') {
                *shell_launcher = false;
            }
            return false;
        }
        if let Position::Wrapped(active) = position {
            if std::mem::take(&mut active.value_next) {
                return false;
            }
            // `command -v ch` looks the command up without running it.
            if active.name == "command" && matches!(token.as_str(), "-v" | "-V") {
                *position = Position::Argument;
                return false;
            }
            if token.len() > 1 && token.starts_with('-') {
                active.value_next = wrapper_option_takes_value(active.name, &token);
                return false;
            }
            if active.name == "timeout" && !active.duration_seen {
                active.duration_seen = true;
                return false;
            }
        }
        if let Some(&name) = COMMAND_WRAPPERS.iter().find(|&&w| w == token) {
            *position = Position::Wrapped(Wrapper {
                name,
                value_next: false,
                duration_seen: false,
            });
            return false;
        }
        if token.contains('=') || SHELL_KEYWORDS.contains(&token.as_str()) {
            return false;
        }
        *position = Position::Argument;
        let basename = token.rsplit('/').next();
        *shell_launcher = matches!(basename, Some("bash" | "sh" | "zsh"));
        matches!(basename, Some("chat-history" | "ch"))
    }

    let mut word = String::new();
    let mut word_quoted = false;
    let mut position = Position::Command;
    let mut shell_launcher = false;
    let mut script_next = false;
    let mut quote = None;
    let mut escaped = false;
    let mut redirect_target_next = false;
    let mut heredocs = Vec::new();
    let mut stdin_heredoc = None;
    // One entry per open `(`: whether it opened `((`/`$((` arithmetic, where
    // `<<` is a shift rather than a heredoc.
    let mut parens = Vec::new();
    let mut chars = command.chars();
    while let Some(ch) = chars.next() {
        if escaped {
            word.push(ch);
            escaped = false;
            continue;
        }
        match quote {
            Some('\'') if ch == '\'' => quote = None,
            Some('"') if ch == '"' => quote = None,
            Some('"') if ch == '\\' => escaped = true,
            // "$(…)" and "`…`" still run their contents.
            Some('"') if ch == '`' || (ch == '$' && chars.clone().next() == Some('(')) => {
                if shell_runs_history(&substitution(&mut chars, ch)) {
                    return true;
                }
            }
            Some(_) => word.push(ch),
            None => match ch {
                '\\' => escaped = true,
                '\'' | '"' => {
                    word_quoted |= word.is_empty();
                    quote = Some(ch);
                }
                // `<<<` is a here-string: its word is data, not a heredoc.
                '<' if chars.as_str().starts_with("<<") => {
                    chars.next();
                    chars.next();
                    word.push_str("<<<");
                }
                // `2>&1`, `>&2` and `&>log` are redirections, not `&` separators.
                '&' if word.ends_with(['>', '<']) || chars.as_str().starts_with('>') => {
                    word.push(ch);
                }
                '<' if chars.clone().next() == Some('<') && !parens.contains(&true) => {
                    if let Some(heredoc) = read_heredoc(&mut chars) {
                        // `2<<ERR` feeds descriptor 2; only descriptor 0 is stdin.
                        let descriptor = if !word_quoted && word.bytes().all(|b| b.is_ascii_digit())
                        {
                            std::mem::take(&mut word)
                        } else {
                            String::new()
                        };
                        if first_word_is_history(
                            &mut word,
                            &mut word_quoted,
                            &mut position,
                            &mut shell_launcher,
                            &mut script_next,
                            &mut redirect_target_next,
                            &mut stdin_heredoc,
                        ) {
                            return true;
                        }
                        if matches!(descriptor.as_str(), "" | "0") {
                            stdin_heredoc = Some(heredocs.len());
                        }
                        heredocs.push(heredoc);
                    } else {
                        word.push(ch);
                    }
                }
                '\n' => {
                    if first_word_is_history(
                        &mut word,
                        &mut word_quoted,
                        &mut position,
                        &mut shell_launcher,
                        &mut script_next,
                        &mut redirect_target_next,
                        &mut stdin_heredoc,
                    ) {
                        return true;
                    }
                    mark_shell_input(&mut heredocs, &mut stdin_heredoc, shell_launcher);
                    position = Position::Command;
                    shell_launcher = false;
                    script_next = false;
                    redirect_target_next = false;
                    for heredoc in std::mem::take(&mut heredocs) {
                        let body = heredoc_body(&mut chars, &heredoc);
                        if (heredoc.shell_input && shell_runs_history(&body))
                            || (!heredoc.shell_input
                                && !heredoc.quoted
                                && expanded_heredoc_runs_history(&body))
                        {
                            return true;
                        }
                    }
                }
                ';' | '&' | '|' | '(' | ')' | '{' | '}' | '`' => {
                    if first_word_is_history(
                        &mut word,
                        &mut word_quoted,
                        &mut position,
                        &mut shell_launcher,
                        &mut script_next,
                        &mut redirect_target_next,
                        &mut stdin_heredoc,
                    ) {
                        return true;
                    }
                    mark_shell_input(&mut heredocs, &mut stdin_heredoc, shell_launcher);
                    position = Position::Command;
                    shell_launcher = false;
                    script_next = false;
                    redirect_target_next = false;
                    if ch == '(' {
                        let arithmetic = chars.clone().next() == Some('(');
                        if arithmetic {
                            chars.next();
                        }
                        parens.push(arithmetic);
                    } else if ch == ')'
                        && parens.pop() == Some(true)
                        && chars.clone().next() == Some(')')
                    {
                        chars.next();
                    }
                }
                ch if ch.is_whitespace() => {
                    if first_word_is_history(
                        &mut word,
                        &mut word_quoted,
                        &mut position,
                        &mut shell_launcher,
                        &mut script_next,
                        &mut redirect_target_next,
                        &mut stdin_heredoc,
                    ) {
                        return true;
                    }
                }
                _ => word.push(ch),
            },
        }
    }
    first_word_is_history(
        &mut word,
        &mut word_quoted,
        &mut position,
        &mut shell_launcher,
        &mut script_next,
        &mut redirect_target_next,
        &mut stdin_heredoc,
    )
}

/// Whether a word is a redirection, and if so whether its target is the
/// next word (`>` alone) rather than attached (`>out`, `2>&1`), and whether
/// it replaces standard input (`<file`, `0<file`, `<<<word`, `<&3`).
fn redirection(token: &str) -> Option<(bool, bool)> {
    let op = token.trim_start_matches(|c: char| c.is_ascii_digit());
    if !(op.starts_with(['>', '<']) || op.starts_with("&>")) {
        return None;
    }
    let descriptor = &token[..token.len() - op.len()];
    let stdin = match descriptor {
        "" => op.starts_with('<'),
        _ => descriptor == "0",
    };
    Some((op.trim_start_matches(['>', '<', '&']).is_empty(), stdin))
}

struct Heredoc {
    delimiter: String,
    quoted: bool,
    strip_tabs: bool,
    shell_input: bool,
}

/// Read the delimiter after `<<`, leaving the original iterator alone for
/// `<<<` or an unsupported/malformed delimiter.
fn read_heredoc(chars: &mut std::str::Chars<'_>) -> Option<Heredoc> {
    let mut rest = chars.clone();
    rest.next()?; // second '<'
    if rest.clone().next() == Some('<') {
        return None;
    }
    let strip_tabs = if rest.clone().next() == Some('-') {
        rest.next();
        true
    } else {
        false
    };
    while matches!(rest.clone().next(), Some(' ' | '\t')) {
        rest.next();
    }
    let mut delimiter = String::new();
    let mut quote = None;
    let mut quoted = false;
    while let Some(ch) = rest.clone().next() {
        if quote.is_none() && (ch.is_whitespace() || ";&|()<>{}".contains(ch)) {
            break;
        }
        rest.next();
        match (quote, ch) {
            (None, '\'' | '"') => {
                quote = Some(ch);
                quoted = true;
            }
            (Some(q), c) if q == c => quote = None,
            (None, '\\') => {
                delimiter.push(rest.next()?);
                quoted = true;
            }
            _ => delimiter.push(ch),
        }
    }
    if delimiter.is_empty() || quote.is_some() {
        return None;
    }
    *chars = rest;
    Some(Heredoc {
        delimiter,
        quoted,
        strip_tabs,
        shell_input: false,
    })
}

/// Consume one heredoc through its exact delimiter line, in redirection order.
fn heredoc_body(chars: &mut std::str::Chars<'_>, heredoc: &Heredoc) -> String {
    let mut body = String::new();
    loop {
        let mut line = String::new();
        let mut newline = false;
        for ch in chars.by_ref() {
            if ch == '\n' {
                newline = true;
                break;
            }
            line.push(ch);
        }
        let comparison = line.strip_suffix('\r').unwrap_or(&line);
        let comparison = if heredoc.strip_tabs {
            comparison.trim_start_matches('\t')
        } else {
            comparison
        };
        if comparison == heredoc.delimiter {
            break;
        }
        body.push_str(&line);
        if !newline {
            break;
        }
        body.push('\n');
    }
    body
}

/// An unquoted heredoc expands substitutions even when its lines are data.
fn expanded_heredoc_runs_history(body: &str) -> bool {
    let mut chars = body.chars();
    let mut escaped = false;
    while let Some(ch) = chars.next() {
        if escaped {
            escaped = false;
        } else if ch == '\\' {
            escaped = true;
        } else if (ch == '`' || (ch == '$' && chars.clone().next() == Some('(')))
            && shell_runs_history(&substitution(&mut chars, ch))
        {
            return true;
        }
    }
    false
}

/// The body of a command substitution whose opener (`` ` `` or `$`) was just
/// read, consuming it through the closing `` ` `` or matching `)`.
fn substitution(chars: &mut std::str::Chars, opener: char) -> String {
    let mut body = String::new();
    if opener == '`' {
        body.extend(chars.take_while(|&c| c != '`'));
        return body;
    }
    chars.next();
    let mut depth = 1;
    for c in chars.by_ref() {
        match c {
            '(' => depth += 1,
            ')' => {
                depth -= 1;
                if depth == 0 {
                    break;
                }
            }
            _ => {}
        }
        body.push(c);
    }
    body
}

/// Text of a tool's output: a string, or text blocks (images are skipped).
/// Long output keeps its start and end, like a tool result in `extract_text`.
pub fn tool_output_text(output: &Value) -> String {
    let text = match output {
        Value::String(s) => s.clone(),
        Value::Array(items) => items
            .iter()
            .filter_map(|item| item.get("text").and_then(Value::as_str))
            .collect::<Vec<_>>()
            .join("\n"),
        _ => String::new(),
    };
    truncate_for_search(&text, 16 * 1024)
}

pub fn extract_text(content: &Value) -> String {
    match content {
        Value::String(s) => s.clone(),
        Value::Array(arr) => {
            let mut parts = Vec::new();
            for block in arr {
                let btype = block.get("type").and_then(Value::as_str).unwrap_or("");
                match btype {
                    // "input_text"/"output_text" are Codex content block types
                    "text" | "input_text" | "output_text" => {
                        if let Some(t) = block.get("text").and_then(Value::as_str) {
                            parts.push(t.to_string());
                        }
                    }
                    "tool_use" => {
                        let name = block.get("name").and_then(Value::as_str).unwrap_or("");
                        let mut tool_parts = vec![format!("[Tool: {name}]")];
                        if let Some(inp) = block.get("input").and_then(Value::as_object) {
                            for key in &[
                                "file_path",
                                "command",
                                "description",
                                "pattern",
                                "query",
                                "prompt",
                                "path",
                            ] {
                                if let Some(Value::String(val)) = inp.get(*key) {
                                    let truncated: String = val.chars().take(200).collect();
                                    tool_parts.push(truncated);
                                }
                            }
                        }
                        parts.push(tool_parts.join(" "));
                    }
                    "tool_result" => match block.get("content") {
                        Some(Value::String(inner)) => {
                            let truncated = truncate_for_search(inner, 16 * 1024);
                            parts.push(format!("[Tool Result] {truncated}"));
                        }
                        Some(Value::Array(arr)) => {
                            for item in arr {
                                if let Some(t) = item.get("text").and_then(Value::as_str) {
                                    let truncated = truncate_for_search(t, 16 * 1024);
                                    parts.push(format!("[Tool Result] {truncated}"));
                                }
                            }
                        }
                        _ => {}
                    },
                    _ => {}
                }
            }
            parts.join(" ")
        }
        _ => String::new(),
    }
}

#[derive(Default)]
pub struct MessageContext {
    pub tools: Vec<String>,
    pub files: Vec<String>,
    pub errors: Vec<String>,
}

pub fn extract_context(content: &Value) -> MessageContext {
    let mut ctx = MessageContext::default();
    let Some(arr) = content.as_array() else {
        return ctx;
    };
    for block in arr {
        let btype = block.get("type").and_then(Value::as_str).unwrap_or("");
        match btype {
            "tool_use" => {
                if let Some(name) = block.get("name").and_then(Value::as_str)
                    && !name.is_empty()
                {
                    ctx.tools.push(name.to_string());
                }
                if let Some(inp) = block.get("input").and_then(Value::as_object) {
                    for key in &["file_path", "path"] {
                        if let Some(Value::String(val)) = inp.get(*key) {
                            ctx.files.push(val.clone());
                        }
                    }
                }
            }
            "tool_result" => {
                let texts: Vec<String> = match block.get("content") {
                    Some(Value::String(s)) => vec![s.clone()],
                    Some(Value::Array(arr)) => arr
                        .iter()
                        .filter_map(|item| {
                            item.get("text").and_then(Value::as_str).map(String::from)
                        })
                        .collect(),
                    _ => Vec::new(),
                };
                for inner in &texts {
                    ctx.errors.extend(error_lines(inner));
                }
            }
            _ => {}
        }
    }
    ctx
}

/// Lines of tool output that report an error, each cut to 200 characters.
pub fn error_lines(text: &str) -> Vec<String> {
    text.lines()
        .filter(|line| {
            let ll = line.to_lowercase();
            ["error", "exception", "traceback", "failed"]
                .iter()
                .any(|w| ll.contains(w))
        })
        .map(|line| line.trim().chars().take(200).collect())
        .collect()
}

pub fn clean_prompt(text: &str) -> String {
    let mut result = CLEAN_USER_QUERY_RE.replace_all(text, "").to_string();
    result = CLEAN_END_QUERY_RE.replace_all(&result, "").to_string();
    result = CLEAN_ATTACHED_RE
        .replace_all(&result, "[attached files]")
        .to_string();
    for re in STRIP_TAG_REGEXES.iter() {
        result = re.replace_all(&result, "").to_string();
    }
    result = CLEAN_MULTI_NL_RE.replace_all(&result, "\n\n").to_string();
    result.trim().to_string()
}

// Preamble tags stripped from titles even when unclosed (truncated prompts
// often cut off before the closing tag). `user_query` is excluded — its body
// IS the title.
static TITLE_PREAMBLE_RES: LazyLock<Vec<Regex>> = LazyLock::new(|| {
    STRIP_TAGS
        .iter()
        .chain(std::iter::once(&"timestamp"))
        .map(|tag| Regex::new(&format!(r"(?s)<{tag}>.*?(</{tag}>|\z)")).unwrap())
        .collect()
});
// Lowercase snake/kebab tags of ≥3 chars: catches machine preamble markup
// while leaving code-like tokens (`Vec<String>`, `<T>`) in titles.
static TITLE_LEFTOVER_TAG_RE: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"</?[a-z][a-z0-9_-]{2,60}>").unwrap());
static TITLE_WS_RE: LazyLock<Regex> = LazyLock::new(|| Regex::new(r"\s+").unwrap());

/// Content-level cleaning for stored first prompts: strips preamble (even
/// when a closing tag is missing) and collapses whitespace, but keeps
/// code-like tokens and adds no display artifacts.
pub fn clean_first_prompt(text: &str) -> String {
    let mut t = clean_prompt(text);
    for re in TITLE_PREAMBLE_RES.iter() {
        t = re.replace_all(&t, " ").to_string();
    }
    TITLE_WS_RE.replace_all(t.trim(), " ").to_string()
}

/// One-line title for list/search rows: [`clean_first_prompt`] plus stray-tag
/// removal and ellipsis truncation on a char boundary. Returns "" when
/// nothing human-readable is left.
pub fn display_title(text: &str, max: usize) -> String {
    let t = clean_first_prompt(text);
    let t = TITLE_LEFTOVER_TAG_RE.replace_all(&t, " ");
    let t = TITLE_WS_RE.replace_all(t.trim(), " ").to_string();
    let mut out: String = t.chars().take(max).collect();
    if t.chars().count() > max {
        out.push('…');
    }
    out
}

pub fn is_noise(text: &str) -> bool {
    let trimmed = text.trim();
    if trimmed.is_empty() {
        return true;
    }
    let lower = trimmed.to_lowercase();
    if START_NOISE.iter().any(|p| lower.starts_with(p)) {
        return true;
    }
    trimmed.chars().count() <= 200 && SHORT_NOISE.iter().any(|p| lower.starts_with(p))
}

/// `<command-name>/x</command-name>…<command-args>y</command-args>` → "/x y".
/// Only an entry that is itself the harness wrapper counts: tool results and
/// pasted diffs that merely quote these tags keep their full text.
pub fn slash_command_text(text: &str) -> Option<String> {
    if !text.trim_start().starts_with("<command-") {
        return None;
    }
    let between = |open: &str, close: &str| {
        let start = text.find(open)? + open.len();
        let end = start + text[start..].find(close)?;
        Some(text[start..end].trim().to_string())
    };
    let args = between("<command-args>", "</command-args>")?;
    if args.is_empty() {
        return None;
    }
    let name = between("<command-name>", "</command-name>").unwrap_or_default();
    Some(format!("{name} {args}").trim().to_string())
}

/// Index the human query when Cursor wraps it in `<user_query>`; otherwise
/// strip known harness tags.
pub fn indexable_user_text(text: &str) -> String {
    let bodies: Vec<String> = USER_QUERY_BODY_RE
        .captures_iter(text)
        .filter_map(|c| c.get(1).map(|m| m.as_str().trim().to_string()))
        .filter(|s| !s.is_empty())
        .collect();
    if !bodies.is_empty() {
        return bodies.join("\n");
    }
    clean_prompt(text)
}

pub fn is_contextual_user_fragment(text: &str) -> bool {
    let t = text.trim();
    if t.is_empty() {
        return false;
    }
    if t.starts_with("# AGENTS.md instructions") && t.contains("</INSTRUCTIONS>") {
        return true;
    }
    const TAGS: &[&str] = &[
        "environment_context",
        "skill",
        "user_shell_command",
        "turn_aborted",
        "subagent_notification",
        "recommended_plugins",
        "codex_internal_context",
        "goal_context",
        "user_instructions",
        "permissions",
    ];
    for tag in TAGS {
        let open = format!("<{tag}");
        if t.starts_with(&open) {
            return true;
        }
    }
    t.starts_with("<external_")
}

pub fn cap_excerpt(text: &str, max_chars: usize) -> String {
    if text.chars().count() <= max_chars {
        return text.to_string();
    }
    let mut out: String = text.chars().take(max_chars.saturating_sub(1)).collect();
    out.push('…');
    out
}

/// Remove CSI/OSC/DCS and other C0/C1 controls from terminal-bound text.
pub fn strip_terminal_controls(input: &str) -> String {
    let chars: Vec<char> = input.chars().collect();
    let mut out = String::with_capacity(input.len());
    let mut i = 0;
    while i < chars.len() {
        let c = chars[i];
        match c {
            '\u{1b}' => {
                if i + 1 >= chars.len() {
                    break;
                }
                match chars[i + 1] {
                    '[' => {
                        i += 2;
                        while i < chars.len() {
                            let n = chars[i];
                            if n.is_control() {
                                break;
                            }
                            i += 1;
                            if ('@'..='~').contains(&n) {
                                break;
                            }
                        }
                        continue;
                    }
                    ']' | 'P' | 'X' | '^' | '_' => {
                        i += 2;
                        while i < chars.len() {
                            let n = chars[i];
                            if n == '\u{7}' {
                                i += 1;
                                break;
                            }
                            if n == '\u{1b}' && i + 1 < chars.len() && chars[i + 1] == '\\' {
                                i += 2;
                                break;
                            }
                            if n.is_control() && n != '\t' {
                                break;
                            }
                            i += 1;
                        }
                        continue;
                    }
                    '\u{20}'..='\u{7e}' => {
                        i += 2;
                        continue;
                    }
                    _ => {
                        i += 1;
                        continue;
                    }
                }
            }
            '\r' => {
                out.push(' ');
                i += 1;
            }
            '\t' | '\n' => {
                out.push(c);
                i += 1;
            }
            '\u{00}'..='\u{1f}' | '\u{7f}' | '\u{80}'..='\u{9f}' => {
                i += 1;
            }
            '\u{202a}'..='\u{202e}' | '\u{2066}'..='\u{2069}' => {
                i += 1;
            }
            _ => {
                out.push(c);
                i += 1;
            }
        }
    }
    out
}

pub fn is_warmup_message(text: &str) -> bool {
    let stripped = text.trim().to_lowercase();
    WARMUP_PATTERNS.contains(&stripped.as_str())
}

pub fn is_clear_metadata(text: &str) -> bool {
    let lower = text.to_lowercase();
    CLEAR_META_PATTERNS.iter().any(|p| lower.contains(p))
}

pub fn is_clear_only_conversation(user_messages: &[String]) -> bool {
    if user_messages.is_empty() {
        return true;
    }
    user_messages.iter().all(|m| {
        let lower = m.trim().to_lowercase();
        lower.is_empty() || lower == "/clear" || lower == "clear" || is_clear_metadata(m)
    })
}

fn find_ci_position(haystack: &str, needle: &str) -> Option<usize> {
    let needle_lower: String = needle.to_lowercase();
    let needle_chars: Vec<char> = needle_lower.chars().collect();
    if needle_chars.is_empty() {
        return Some(0);
    }
    for (i, _) in haystack.char_indices() {
        let mut chars = haystack[i..].chars();
        let mut matched = true;
        for &nc in &needle_chars {
            match chars.next() {
                Some(hc) if hc.to_lowercase().next() == Some(nc) => {}
                _ => {
                    matched = false;
                    break;
                }
            }
        }
        if matched {
            return Some(i);
        }
    }
    None
}

pub fn snippet_around_match(text: &str, query: &str, context_chars: usize) -> String {
    let cleaned = clean_prompt(text);
    let query_terms: Vec<&str> = {
        let terms: Vec<&str> = query.split_whitespace().filter(|w| w.len() > 2).collect();
        if terms.is_empty() {
            query.split_whitespace().filter(|w| w.len() >= 2).collect()
        } else {
            terms
        }
    };
    let query_lower: Vec<String> = query_terms.iter().map(|t| t.to_lowercase()).collect();

    let phrase: String = query_lower.join(" ");
    let best_pos = if let Some(pos) = find_ci_position(&cleaned, &phrase) {
        pos
    } else {
        let mut positions = Vec::new();
        for t in &query_lower {
            if let Some(p) = find_ci_position(&cleaned, t) {
                positions.push(p);
            }
        }
        if positions.is_empty() {
            return cleaned.chars().take(context_chars).collect();
        }
        *positions.iter().min().unwrap()
    };

    let start = cleaned.floor_char_boundary(best_pos.saturating_sub(context_chars / 4));
    let end = cleaned.ceil_char_boundary((start + context_chars).min(cleaned.len()));

    let start = if start > 0 {
        let search_end = cleaned.ceil_char_boundary(start.saturating_add(30).min(cleaned.len()));
        cleaned[start..search_end]
            .find(' ')
            .map(|ws| start + ws + 1)
            .unwrap_or(start)
    } else {
        start
    };
    let end = if end < cleaned.len() {
        let search_start = cleaned.floor_char_boundary(end.saturating_sub(30));
        cleaned[search_start..end]
            .rfind(' ')
            .map(|ws| search_start + ws)
            .unwrap_or(end)
    } else {
        end
    };

    let end = end.max(start);
    let snippet = &cleaned[start..end.min(cleaned.len())];
    let prefix = if start > 0 { "..." } else { "" };
    let suffix = if end < cleaned.len() { "..." } else { "" };
    format!("{prefix}{snippet}{suffix}")
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn history_commands_are_recognised_in_command_position() {
        for cmd in [
            "chat-history search \"auth\" --json",
            "ch view abc123 --plain | grep -n foo",
            "~/.cargo/bin/chat-history inspect abc",
            "./target/release/chat-history search q",
            "FOO=1 NO_COLOR=1 chat-history search q",
            "cd /tmp && chat-history --from yesterday",
            "(cd x; ch search q)",
            "time chat-history search q",
            "for id in a b; do chat-history inspect $id; done",
            "if true; then ch search q; fi",
            "while read id; do ch view $id --plain; done < ids",
            "echo \"$(chat-history search q)\"",
            "out=\"$(ch search q --json)\"",
            "echo \"`chat-history search q`\"",
            "bash -lc 'chat-history search q'",
            "sh -c \"ch view abc --plain\"",
            "tools.exec_command({cmd:`chat-history search '${q}' --json`})",
            "{\"cmd\":\"chat-history view abc --plain\"}",
            "echo start\nchat-history search q",
        ] {
            assert!(is_history_command(cmd), "{cmd}");
        }
        for cmd in [
            "cd ~/GitHub/chat-history && cargo test",
            "git log | grep chat-history",
            "rg 'chat-history' README.md",
            "rg \"chat-history; ch\" README.md",
            "echo \"ch search old chats\"",
            "bash -lc 'rg \"chat-history\" README.md'",
            "tools.exec_command({cmd:`rg 'chat-history' README.md`})",
            "rg ch src",
            "for f in chat-history ch; do echo $f; done",
            "echo \"$(rg chat-history README.md)\"",
            "echo \"cost: $5 (chat-history)\"",
            "cat chat-history.md",
            "./target/release/chat-history-bounded search q",
            "python3 compare.py",
            "echo ch",
        ] {
            assert!(!is_history_command(cmd), "{cmd}");
        }
    }

    #[test]
    fn wrapper_options_and_operands_precede_the_command() {
        for cmd in [
            "sudo -E chat-history search q",
            "sudo -u me ch view id",
            "sudo --user=me -- ch view id",
            "timeout 60 chat-history search q",
            "timeout -s KILL 5s ch search q",
            "timeout --kill-after=2 10 ch search q",
            "nice -n 10 chat-history search q",
            "nice -5 ch search q",
            "env -u HOME CHAT_HISTORY_NO_CACHE=1 ch search q",
            "time -p ch search q",
            "exec -a name chat-history search q",
            "nohup nice -n 5 timeout 30 ch search q",
            "cd /tmp && timeout 60 ch search q",
        ] {
            assert!(is_history_command(cmd), "{cmd}");
        }
        for cmd in [
            "command -v chat-history",
            "command -V ch",
            "timeout 60 rg chat-history README.md",
            "nice -n 10 cargo test chat-history",
            "sudo -u ch ls",
            "timeout ch",
        ] {
            assert!(!is_history_command(cmd), "{cmd}");
        }
    }

    #[test]
    fn heredoc_data_is_not_a_shell_command() {
        for cmd in [
            "cat > guide.md <<'EOF'\nchat-history search q\nEOF",
            "python3 - <<'PY'\nch search q\nPY",
            "cat <<EOF\nchat-history search q\nEOF",
            "cat <<-'EOF'\n\tch search q\n\tEOF",
            "cat <<'FIRST' <<'SECOND'\nch search q\nFIRST\nchat-history view id\nSECOND",
            "bash script.sh <<'EOF'\nch search q\nEOF",
            "bash -lc 'echo ready' <<'EOF'\nch search q\nEOF",
            "bash <<'EOF' -c 'echo ready'\nch search q\nEOF",
            "bash <<'EOF' script.sh\nch search q\nEOF",
            "bash <<'FIRST' <<'SECOND'\nch search q\nFIRST\necho ready\nSECOND",
            "bash <<'FIRST'; cat <<'SECOND'\necho ready\nFIRST\nch search q\nSECOND",
            "cat <<< 'ch search q'",
            "bash script.sh >out <<'EOF'\nch search q\nEOF",
            "bash <<'EOF' < /dev/null\nch search q\nEOF",
            "bash <<'EOF' </dev/null\nch search q\nEOF",
            "bash <<'EOF' 0</dev/null\nch search q\nEOF",
            "bash <<'EOF' <<< 'echo ready'\nch search q\nEOF",
        ] {
            assert!(!is_history_command(cmd), "{cmd}");
        }
    }

    #[test]
    fn executable_commands_in_and_after_heredocs_are_recognised() {
        for cmd in [
            "cat <<EOF\n$(chat-history search q)\nEOF",
            "cat <<EOF\n`ch search q`\nEOF",
            "bash <<'EOF'\nch search q\nEOF",
            "sh <<EOF\nchat-history search q\nEOF",
            "cat <<'EOF'\nch search q\nEOF\nchat-history view id",
            "bash <<'FIRST' <<'SECOND'\necho ignored\nFIRST\nch search q\nSECOND",
            "bash <<'EOF'; echo ready\nch search q\nEOF",
            "cat <<'FIRST'; bash <<'SECOND'\nch search q\nFIRST\nch view id\nSECOND",
            "cat <<< \"x\"\nchat-history search q",
            "grep -c a <<< \"$x\"; ch view id",
            "bash <<'EOF' >out\nch search q\nEOF",
            "bash >out <<'EOF'\nch search q\nEOF",
            "bash <<'EOF' 2>&1 >>log\nch search q\nEOF",
            "diff <(chat-history search a 2>/dev/null) <(ch search b)",
            "echo $((1<<4))\nch search q",
            "(( x << 2 )) && ch search q",
            "(( x << 2 ))\nch search q\n2",
            "echo $(( (1 << 2) + 1 ))\nch search q",
            "((cd /tmp; ch search q))",
            "bash -c '>log chat-history search q'",
            "sh -c \"2>/dev/null ch search q\"",
            "bash -c 'echo ok' 2>/dev/null <<'EOF'; ch view id\nx\nEOF",
            "bash 2<<'ERR' <<'SCRIPT'\nignored\nERR\nch search q\nSCRIPT",
            "bash 3<<'X' 0<<'SCRIPT'\nignored\nX\nch search q\nSCRIPT",
            "bash < /dev/null <<'EOF'\nch search q\nEOF",
            "bash <<'SCRIPT' 2<<'ERR'\nch search q\nSCRIPT\nignored\nERR",
        ] {
            assert!(is_history_command(cmd), "{cmd}");
        }
        assert!(!is_history_command("cat <<EOF\n\\$(ch search q)\nEOF"));
    }

    #[test]
    fn tool_output_text_reads_strings_and_text_blocks() {
        assert_eq!(tool_output_text(&json!("plain out")), "plain out");
        assert_eq!(
            tool_output_text(&json!([
                {"type": "text", "text": "one"},
                {"type": "image", "source": {}},
                {"type": "input_text", "text": "two"}
            ])),
            "one\ntwo"
        );
        let long = "x".repeat(40 * 1024);
        assert!(tool_output_text(&json!(long)).len() <= 16 * 1024 + 1);
    }

    #[test]
    fn extract_text_from_string() {
        let v = json!("hello world");
        assert_eq!(extract_text(&v), "hello world");
    }

    #[test]
    fn extract_text_from_array() {
        let v = json!([
            {"type": "text", "text": "hello"},
            {"type": "text", "text": "world"}
        ]);
        assert_eq!(extract_text(&v), "hello world");
    }

    #[test]
    fn extract_text_tool_use() {
        let v = json!([
            {"type": "tool_use", "name": "Read", "input": {"file_path": "/src/main.rs"}}
        ]);
        let text = extract_text(&v);
        assert!(text.contains("Read"));
        assert!(text.contains("/src/main.rs"));
    }

    #[test]
    fn extract_text_tool_result_string() {
        let v = json!([
            {"type": "tool_result", "content": "some output text"}
        ]);
        let text = extract_text(&v);
        assert!(text.contains("some output text"));
    }

    #[test]
    fn extract_text_tool_result_array() {
        let v = json!([
            {"type": "tool_result", "content": [{"text": "result line"}]}
        ]);
        let text = extract_text(&v);
        assert!(text.contains("result line"));
    }

    #[test]
    fn extract_text_null() {
        assert_eq!(extract_text(&json!(null)), "");
    }

    #[test]
    fn extract_text_number() {
        assert_eq!(extract_text(&json!(42)), "");
    }

    #[test]
    fn clean_prompt_strips_user_query_tags() {
        assert_eq!(
            clean_prompt("<user_query> hello world </user_query>"),
            "hello world"
        );
    }

    #[test]
    fn clean_prompt_strips_attached_files() {
        let text = "hello <attached_files>some files here</attached_files> world";
        assert_eq!(clean_prompt(text), "hello [attached files] world");
    }

    #[test]
    fn clean_prompt_collapses_newlines() {
        assert_eq!(clean_prompt("hello\n\n\n\n\nworld"), "hello\n\nworld");
    }

    #[test]
    fn clean_prompt_strips_hyphenated_system_reminder() {
        // Claude Code injects hyphenated <system-reminder> blocks into user
        // message text; Cursor uses the underscore form.
        let text = "<system-reminder>\ninjected boilerplate\n</system-reminder>\nfix the login bug";
        assert_eq!(clean_prompt(text), "fix the login bug");
    }

    #[test]
    fn clean_prompt_strips_system_tags() {
        let text = "hello <system_reminder>internal stuff</system_reminder> world";
        assert_eq!(clean_prompt(text), "hello  world");
    }

    #[test]
    fn is_noise_empty_and_whitespace() {
        assert!(is_noise(""));
        assert!(is_noise("   "));
        assert!(is_noise("\t\n"));
        assert!(is_noise("  \n  \t  "));
    }

    #[test]
    fn is_noise_allows_short_messages() {
        assert!(!is_noise("hi"));
        assert!(!is_noise("ok"));
        assert!(!is_noise("yes"));
        assert!(!is_noise("no"));
        assert!(!is_noise("y"));
        assert!(!is_noise("n"));
        assert!(!is_noise("fix ci"));
        assert!(!is_noise("ls -la"));
        assert!(!is_noise("git rebase"));
        assert!(!is_noise("run tests"));
        assert!(!is_noise("do it"));
        assert!(!is_noise("why?"));
        assert!(!is_noise("thanks"));
    }

    #[test]
    fn is_noise_all_known_patterns() {
        assert!(is_noise(
            "this session is being continued from a previous conversation with extra context"
        ));
        assert!(is_noise(
            "caveat: the messages below were generated by the user while running local commands.\n<command-name>/x</command-name>"
        ));
        assert!(is_noise("You are Claude Code, an AI assistant"));
        assert!(is_noise("I'm currently in read-only mode"));
        assert!(is_noise("I cannot make changes to files"));
        assert!(is_noise("I'm in plan mode right now"));
        assert!(is_noise("Hello! I'm Claude, ready to help"));
        assert!(is_noise("I am Claude and I can help"));
        assert!(is_noise("I'm ready to help you with your project"));
        assert!(is_noise("What would you like me to work on?"));
        assert!(is_noise("How can I assist you today?"));
        assert!(is_noise("I understand that I'm in a sandbox"));
    }

    #[test]
    fn is_noise_does_not_drop_substantive_messages_on_substring_match() {
        assert!(!is_noise("caveat: some important note here"));
        assert!(!is_noise(&format!(
            "here is a pasted log with caveat: inside it\n{}",
            "x".repeat(500)
        )));
        let long_greeting = format!(
            "Hello! I'm Claude, ready to help with a long pasted log\n{}",
            "line\n".repeat(80)
        );
        assert!(long_greeting.chars().count() > 200);
        assert!(!is_noise(&long_greeting));
    }

    #[test]
    fn is_noise_patterns_are_case_insensitive() {
        assert!(is_noise("YOU ARE CLAUDE CODE, an advanced AI"));
        assert!(is_noise("Hello! I'M CLAUDE, ready to help"));
        assert!(is_noise("HOW CAN I ASSIST you?"));
    }

    #[test]
    fn is_noise_valid_content() {
        assert!(!is_noise("rebuild docker container with new config"));
        assert!(!is_noise("implement the authentication system"));
    }

    #[test]
    fn is_noise_does_not_false_positive_on_substrings() {
        assert!(!is_noise("the session data is persisted to disk"));
        assert!(!is_noise("help me understand the codebase"));
        assert!(!is_noise("make changes to the parser module"));
        assert!(!is_noise("I'm working on plan mode switching logic"));
    }

    #[test]
    fn is_noise_unicode_and_punctuation() {
        assert!(!is_noise("日本語テスト"));
        assert!(!is_noise("café"));
        assert!(!is_noise("..."));
        assert!(!is_noise("???"));
        assert!(!is_noise("🚀"));
    }

    #[test]
    fn slash_command_text_keeps_arguments() {
        let text =
            "<command-name>/code-review</command-name>\n<command-args>foo bar</command-args>";
        assert_eq!(
            slash_command_text(text).as_deref(),
            Some("/code-review foo bar")
        );
        assert_eq!(
            slash_command_text("<command-name>/x</command-name>").as_deref(),
            None
        );
        // A tool result or diff quoting the wrapper is ordinary content.
        let quoted = format!("diff --git a/x b/x\n+{text}\n context");
        assert_eq!(slash_command_text(&quoted), None);
        assert_eq!(
            slash_command_text(&format!("\n  {text}")).as_deref(),
            Some("/code-review foo bar")
        );
    }

    #[test]
    fn indexable_user_text_keeps_only_user_query_bodies() {
        let text = "<documentation_context>skill body history</documentation_context>\n<user_query>\nreview the parser\n</user_query>";
        assert_eq!(indexable_user_text(text), "review the parser");
        assert!(!indexable_user_text(text).contains("skill body"));
    }

    #[test]
    fn strip_terminal_controls_keeps_newline_and_cjk_after_esc() {
        assert_eq!(strip_terminal_controls("a\u{1b}[31\nb"), "a\nb");
        assert_eq!(strip_terminal_controls("x\u{1b}日本"), "x日本");
        let injected = "hi\u{1b}]0;evil title\u{7} there";
        assert_eq!(strip_terminal_controls(injected), "hi there");
        assert!(!strip_terminal_controls("\u{1b}]52;c;secret\u{7}visible").contains("secret"));
        assert_eq!(
            strip_terminal_controls("\u{1b}]52;c;secret\u{7}visible"),
            "visible"
        );
    }

    #[test]
    fn cap_excerpt_limits_characters() {
        let long = "x".repeat(500);
        let capped = cap_excerpt(&long, 400);
        assert_eq!(capped.chars().count(), 400);
        assert!(capped.ends_with('…'));
    }

    #[test]
    fn warmup_messages() {
        assert!(is_warmup_message("warmup"));
        assert!(is_warmup_message("/clear"));
        assert!(is_warmup_message("  /clear  "));
        assert!(!is_warmup_message("hello world"));
        assert!(!is_warmup_message("clear the cache"));
    }

    #[test]
    fn clear_only_conversation_empty() {
        assert!(is_clear_only_conversation(&[]));
    }

    #[test]
    fn clear_only_conversation_clear_messages() {
        assert!(is_clear_only_conversation(&["/clear".to_string()]));
        assert!(is_clear_only_conversation(&[
            "clear".to_string(),
            "/clear".to_string()
        ]));
    }

    #[test]
    fn clear_only_conversation_real_messages() {
        assert!(!is_clear_only_conversation(&[
            "implement feature X".to_string()
        ]));
    }

    #[test]
    fn snippet_contains_query_term() {
        let text = "This is a long piece of text about implementing authentication with OAuth2 tokens and JWT validation for the API endpoint";
        let snippet = snippet_around_match(text, "authentication", 100);
        assert!(snippet.contains("authentication"));
    }

    #[test]
    fn snippet_fallback_on_no_match() {
        let text = "This is a long piece of text about implementing stuff for the project with lots of details";
        let snippet = snippet_around_match(text, "nonexistent_xyz_term", 100);
        assert!(!snippet.is_empty());
    }

    #[test]
    fn snippet_short_text() {
        let snippet = snippet_around_match("short text here", "short", 200);
        assert!(snippet.contains("short"));
    }

    #[test]
    fn snippet_does_not_panic_on_empty() {
        let snippet = snippet_around_match("", "query", 100);
        assert!(snippet.is_empty() || snippet.len() < 100);
    }

    #[test]
    fn extract_context_tool_uses() {
        let v = json!([
            {"type": "tool_use", "name": "Read", "input": {"file_path": "/src/main.rs"}},
            {"type": "tool_use", "name": "Edit", "input": {"file_path": "/src/lib.rs"}}
        ]);
        let ctx = extract_context(&v);
        assert_eq!(ctx.tools, vec!["Read", "Edit"]);
        assert_eq!(ctx.files, vec!["/src/main.rs", "/src/lib.rs"]);
    }

    #[test]
    fn extract_context_errors_from_tool_result() {
        let v = json!([
            {"type": "tool_result", "content": "Error: file not found\nSuccess: done"}
        ]);
        let ctx = extract_context(&v);
        assert_eq!(ctx.errors.len(), 1);
        assert!(ctx.errors[0].contains("Error"));
    }

    #[test]
    fn extract_context_no_tools() {
        let v = json!([{"type": "text", "text": "just text"}]);
        let ctx = extract_context(&v);
        assert!(ctx.tools.is_empty());
        assert!(ctx.files.is_empty());
        assert!(ctx.errors.is_empty());
    }

    #[test]
    fn extract_context_non_array() {
        let v = json!("just a string");
        let ctx = extract_context(&v);
        assert!(ctx.tools.is_empty());
    }

    #[test]
    fn is_clear_metadata_positive() {
        assert!(is_clear_metadata(
            "caveat: the messages below were generated by the user while running local commands"
        ));
        assert!(is_clear_metadata("some text with <command-name> tag"));
    }

    #[test]
    fn is_clear_metadata_negative() {
        assert!(!is_clear_metadata("implement the new feature"));
    }

    #[test]
    fn truncate_for_search_short() {
        assert_eq!(truncate_for_search("short", 100), "short");
    }

    #[test]
    fn truncate_for_search_long() {
        let long = "a".repeat(1000);
        let result = truncate_for_search(&long, 100);
        assert!(result.len() <= 200); // head + tail with space
    }

    #[test]
    fn display_title_strips_unclosed_preamble_tag() {
        let raw =
            "<manually_attached_skills>\nThe user has manually attached the following skills t";
        assert_eq!(display_title(raw, 80), "");
    }

    #[test]
    fn display_title_keeps_text_after_closed_preamble() {
        let raw =
            "<manually_attached_skills>skill stuff</manually_attached_skills>\nfix the login bug";
        assert_eq!(display_title(raw, 80), "fix the login bug");
    }

    #[test]
    fn display_title_collapses_newlines_to_one_line() {
        let raw = "fix the\n\nlogin   bug\ttoday";
        assert_eq!(display_title(raw, 80), "fix the login bug today");
    }

    #[test]
    fn display_title_truncates_with_ellipsis() {
        let raw = "a".repeat(100);
        let out = display_title(&raw, 10);
        assert_eq!(out.chars().count(), 11);
        assert!(out.ends_with('…'));
    }

    #[test]
    fn display_title_keeps_code_like_tokens() {
        assert_eq!(
            display_title("implement Vec<String> parsing for <T>", 80),
            "implement Vec<String> parsing for <T>"
        );
    }

    #[test]
    fn clean_first_prompt_no_ellipsis_and_keeps_code_tokens() {
        let raw = format!(
            "<manually_attached_skills>\nstuff\n</manually_attached_skills>\nfix Vec<String> bug {}",
            "y".repeat(400)
        );
        let out = clean_first_prompt(&raw);
        assert!(out.starts_with("fix Vec<String> bug"));
        assert!(!out.contains('…'));
        assert!(!out.contains("manually_attached_skills"));
    }

    #[test]
    fn display_title_strips_stray_tags_and_keeps_user_query_body() {
        let raw = "<user_query>how do I deploy this?</user_query>";
        assert_eq!(display_title(raw, 80), "how do I deploy this?");
        let raw2 = "<timestamp>2026-07-22T10:00:00Z</timestamp>ship the release";
        assert_eq!(display_title(raw2, 80), "ship the release");
    }
}
