use regex::Regex;
use serde_json::Value;
use std::sync::LazyLock;

static CLEAN_USER_QUERY_RE: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"<user_query>\s*").unwrap());
static CLEAN_END_QUERY_RE: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"\s*</user_query>").unwrap());
static CLEAN_ATTACHED_RE: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"(?s)<attached_files>.*?</attached_files>").unwrap());
static CLEAN_MULTI_NL_RE: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"\n{3,}").unwrap());

static STRIP_TAGS: &[&str] = &[
    "open_and_recently_viewed_files", "user_info", "system_reminder",
    "git_status", "external_links", "rules", "agent_skills",
];

static STRIP_TAG_REGEXES: LazyLock<Vec<Regex>> = LazyLock::new(|| {
    STRIP_TAGS
        .iter()
        .map(|tag| Regex::new(&format!(r"(?s)<{tag}>.*?</{tag}>")).unwrap())
        .collect()
});

static NOISE_PATTERNS: &[&str] = &[
    "this session is being continued", "caveat:", "you are claude code",
    "read-only mode", "i cannot make changes", "i'm in plan mode",
    "hello! i'm claude", "i am claude", "ready to help you",
    "what would you like me to", "how can i assist", "i understand that i'm",
];

static WARMUP_PATTERNS: &[&str] = &["warmup", "/clear"];

static CLEAR_META_PATTERNS: &[&str] = &[
    "caveat: the messages below were generated by the user while running local commands",
    "<command-name>", "</command-name>", "<local-command-stdout>",
];

fn truncate_for_search(s: &str, max: usize) -> String {
    if s.len() <= max {
        return s.to_owned();
    }
    let head_end = s.floor_char_boundary(max * 3 / 4);
    let tail_start = s.ceil_char_boundary(s.len().saturating_sub(max / 4));
    format!("{} {}", &s[..head_end], &s[tail_start..])
}

pub fn extract_text(content: &Value) -> String {
    match content {
        Value::String(s) => s.clone(),
        Value::Array(arr) => {
            let mut parts = Vec::new();
            for block in arr {
                let btype = block.get("type").and_then(Value::as_str).unwrap_or("");
                match btype {
                    "text" => {
                        if let Some(t) = block.get("text").and_then(Value::as_str) {
                            parts.push(t.to_string());
                        }
                    }
                    "tool_use" => {
                        let name = block.get("name").and_then(Value::as_str).unwrap_or("");
                        let mut tool_parts = vec![format!("[Tool: {name}]")];
                        if let Some(inp) = block.get("input").and_then(Value::as_object) {
                            for key in &["file_path", "command", "description", "pattern", "query", "prompt", "path"] {
                                if let Some(Value::String(val)) = inp.get(*key) {
                                    let truncated: String = val.chars().take(200).collect();
                                    tool_parts.push(truncated);
                                }
                            }
                        }
                        parts.push(tool_parts.join(" "));
                    }
                    "tool_result" => {
                        match block.get("content") {
                            Some(Value::String(inner)) => {
                                let truncated = truncate_for_search(inner, 16 * 1024);
                                parts.push(format!("[Tool Result] {truncated}"));
                            }
                            Some(Value::Array(arr)) => {
                                for item in arr {
                                    if let Some(t) = item.get("text").and_then(Value::as_str) {
                                        let truncated = truncate_for_search(t, 16 * 1024);
                                        parts.push(format!("[Tool Result] {truncated}"));
                                    }
                                }
                            }
                            _ => {}
                        }
                    }
                    _ => {}
                }
            }
            parts.join(" ")
        }
        _ => String::new(),
    }
}

#[derive(Default)]
pub struct MessageContext {
    pub tools: Vec<String>,
    pub files: Vec<String>,
    pub errors: Vec<String>,
}

pub fn extract_context(content: &Value) -> MessageContext {
    let mut ctx = MessageContext::default();
    let Some(arr) = content.as_array() else {
        return ctx;
    };
    for block in arr {
        let btype = block.get("type").and_then(Value::as_str).unwrap_or("");
        match btype {
            "tool_use" => {
                if let Some(name) = block.get("name").and_then(Value::as_str) {
                    if !name.is_empty() {
                        ctx.tools.push(name.to_string());
                    }
                }
                if let Some(inp) = block.get("input").and_then(Value::as_object) {
                    for key in &["file_path", "path"] {
                        if let Some(Value::String(val)) = inp.get(*key) {
                            ctx.files.push(val.clone());
                        }
                    }
                }
            }
            "tool_result" => {
                let texts: Vec<String> = match block.get("content") {
                    Some(Value::String(s)) => vec![s.clone()],
                    Some(Value::Array(arr)) => arr.iter()
                        .filter_map(|item| item.get("text").and_then(Value::as_str).map(String::from))
                        .collect(),
                    _ => Vec::new(),
                };
                for inner in &texts {
                    for line in inner.lines() {
                        let ll = line.to_lowercase();
                        if ["error", "exception", "traceback", "failed"]
                            .iter()
                            .any(|w| ll.contains(w))
                        {
                            let truncated: String = line.trim().chars().take(200).collect();
                            ctx.errors.push(truncated);
                        }
                    }
                }
            }
            _ => {}
        }
    }
    ctx
}

pub fn clean_prompt(text: &str) -> String {
    let mut result = CLEAN_USER_QUERY_RE.replace_all(text, "").to_string();
    result = CLEAN_END_QUERY_RE.replace_all(&result, "").to_string();
    result = CLEAN_ATTACHED_RE.replace_all(&result, "[attached files]").to_string();
    for re in STRIP_TAG_REGEXES.iter() {
        result = re.replace_all(&result, "").to_string();
    }
    result = CLEAN_MULTI_NL_RE.replace_all(&result, "\n\n").to_string();
    result.trim().to_string()
}

pub fn is_noise(text: &str) -> bool {
    if text.len() < 40 {
        return true;
    }
    let lower = text.to_lowercase();
    NOISE_PATTERNS.iter().any(|p| lower.contains(p))
}

pub fn is_warmup_message(text: &str) -> bool {
    let stripped = text.trim().to_lowercase();
    WARMUP_PATTERNS.contains(&stripped.as_str())
}

pub fn is_clear_metadata(text: &str) -> bool {
    let lower = text.to_lowercase();
    CLEAR_META_PATTERNS.iter().any(|p| lower.contains(p))
}

pub fn is_clear_only_conversation(user_messages: &[String]) -> bool {
    if user_messages.is_empty() {
        return true;
    }
    user_messages.iter().all(|m| {
        let lower = m.trim().to_lowercase();
        lower.is_empty() || lower == "/clear" || lower == "clear" || is_clear_metadata(m)
    })
}

fn find_ci_position(haystack: &str, needle: &str) -> Option<usize> {
    let needle_lower: String = needle.to_lowercase();
    let needle_chars: Vec<char> = needle_lower.chars().collect();
    if needle_chars.is_empty() {
        return Some(0);
    }
    for (i, _) in haystack.char_indices() {
        let mut chars = haystack[i..].chars();
        let mut matched = true;
        for &nc in &needle_chars {
            match chars.next() {
                Some(hc) if hc.to_lowercase().next() == Some(nc) => {}
                _ => { matched = false; break; }
            }
        }
        if matched {
            return Some(i);
        }
    }
    None
}

pub fn snippet_around_match(text: &str, query: &str, context_chars: usize) -> String {
    let cleaned = clean_prompt(text);
    let query_terms: Vec<&str> = {
        let terms: Vec<&str> = query.split_whitespace().filter(|w| w.len() > 2).collect();
        if terms.is_empty() {
            query.split_whitespace().filter(|w| w.len() >= 2).collect()
        } else {
            terms
        }
    };
    let query_lower: Vec<String> = query_terms.iter().map(|t| t.to_lowercase()).collect();

    let phrase: String = query_lower.join(" ");
    let best_pos = if let Some(pos) = find_ci_position(&cleaned, &phrase) {
        pos
    } else {
        let mut positions = Vec::new();
        for t in &query_lower {
            if let Some(p) = find_ci_position(&cleaned, t) {
                positions.push(p);
            }
        }
        if positions.is_empty() {
            return cleaned.chars().take(context_chars).collect();
        }
        *positions.iter().min().unwrap()
    };

    let start = cleaned.floor_char_boundary(best_pos.saturating_sub(context_chars / 4));
    let end = cleaned.ceil_char_boundary((start + context_chars).min(cleaned.len()));

    let start = if start > 0 {
        let search_end = cleaned.ceil_char_boundary(start.saturating_add(30).min(cleaned.len()));
        cleaned[start..search_end]
            .find(' ')
            .map(|ws| start + ws + 1)
            .unwrap_or(start)
    } else {
        start
    };
    let end = if end < cleaned.len() {
        let search_start = cleaned.floor_char_boundary(end.saturating_sub(30));
        cleaned[search_start..end]
            .rfind(' ')
            .map(|ws| search_start + ws)
            .unwrap_or(end)
    } else {
        end
    };

    let snippet = &cleaned[start..end.min(cleaned.len())];
    let prefix = if start > 0 { "..." } else { "" };
    let suffix = if end < cleaned.len() { "..." } else { "" };
    format!("{prefix}{snippet}{suffix}")
}
